language: php
php:
  - 5.6
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]
branches:
  only:
    - develop
    - master
    - imbo-2.x
services:
  - mongodb
  - memcached
before_install:
  - pecl list
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - printf "\n" | pecl install mongo-1.6.14
  - printf "\n" | pecl install memcached-2.2.0
  - printf "\n" | pecl install imagick-3.4.3
  - pecl list
before_script:
  - phpenv config-add tests/travis-php.ini
  - composer self-update
  - composer -n --no-ansi install --dev --prefer-source
script:
  - ./vendor/bin/phpunit --verbose -c tests/phpunit/phpunit.xml.travis
  - ./vendor/bin/behat --strict --profile no-cc --config tests/behat/behat.yml
after_failure:
  - echo "Tests failed - httpd log follows"
  - echo "================================"
  - cat build/logs/httpd.log
