language: php
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]

branches:
  only:
    - develop
    - master

services:
  - mongodb
  - mysql

before_install:
  - pecl list
  - php -i
  - printf "\n" | pecl install --force mongodb
  - printf "\n" | pecl install imagick
  - mysql -e "CREATE DATABASE IF NOT EXISTS imbo_test;" -u root
  - mysql -e "CREATE USER imbo_test@localhost IDENTIFIED BY 'imbo_test';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON imbo_test.* TO imbo_test@localhost;" -u root
  - mysql -e "GRANT SUPER ON *.* TO 'imbo_test'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;" -u root

before_script:
  - phpenv config-rm xdebug.ini
  - echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer lint
  - composer prepare
  - composer install --prefer-dist
  - composer dev

script:
  - ./vendor/bin/phpunit --verbose -c phpunit.xml.travis
  - ./vendor/bin/behat --strict

after_failure:
  - echo "Tests failed - httpd log follows"
  - echo "================================"
  - cat build/logs/httpd.log
