services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  mysql:
    image: mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imbo_test
      MYSQL_USER: imbo_test
      MYSQL_PASSWORD: imbo_test
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  adminer:
    depends_on:
      - mysql
    image: adminer:latest
    ports:
      - "8888:8080"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
